//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftEngProjectAPIwSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventsList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventsList()
        {
            this.Comments = new HashSet<Comments>();
            this.Product = new HashSet<Product>();
        }
    
        public int eventId { get; set; }
        public string title { get; set; }
        public string detail { get; set; }
        public int artistId { get; set; }
        public string date { get; set; }
        public int guestCount { get; set; }
        public int guestLimit { get; set; }
        public int VIPLimit { get; set; }
        public string address { get; set; }
        public string location { get; set; }
        public string contacts { get; set; }
        public int price { get; set; }
        public int categoryId { get; set; }
        public string imageURL { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
