//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftEngProjectAPIwSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int productId { get; set; }
        public int eventId { get; set; }
        public string imageURL { get; set; }
        public string title { get; set; }
        public string detail { get; set; }
        public int size { get; set; }
        public int price { get; set; }
        public int discountId { get; set; }
    
        public virtual EventsList EventsList { get; set; }
    }
}
