//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserDataAccessProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int adminId { get; set; }
        public int organizerId { get; set; }
        public int userId { get; set; }
    
        public virtual Organizer Organizer { get; set; }
        public virtual User User { get; set; }
    }
}
